const COIN_ABI = {
  bridgeFactory: [
    {
      type: 'constructor',
      stateMutability: 'nonpayable',
      inputs: [{
        type: 'address',
        name: '_bridge',
        internalType: 'address'
      }]
    }, {
      type: 'event',
      name: 'OwnershipTransferred',
      inputs: [{
        type: 'address',
        name: 'previousOwner',
        internalType: 'address',
        indexed: true
      }, {
        type: 'address',
        name: 'newOwner',
        internalType: 'address',
        indexed: true
      }],
      anonymous: false
    }, {
      type: 'event',
      name: 'TokenTargetCreated',
      inputs: [{
        type: 'address',
        name: 'tokenSrc',
        internalType: 'address',
        indexed: true
      }, {
        type: 'address',
        name: 'tokenTag',
        internalType: 'address',
        indexed: true
      }, {
        type: 'address',
        name: 'opt',
        internalType: 'address',
        indexed: false
      }],
      anonymous: false
    }, {
      type: 'function',
      stateMutability: 'nonpayable',
      outputs: [],
      name: 'bindAddress',
      inputs: [{
        type: 'address',
        name: '_tokenSrc',
        internalType: 'address'
      }, {
        type: 'address',
        name: '_tokenTag',
        internalType: 'address'
      }]
    }, {
      type: 'function',
      stateMutability: 'view',
      outputs: [{
        type: 'address',
        name: '',
        internalType: 'address'
      }],
      name: 'bridge',
      inputs: []
    }, {
      type: 'function',
      stateMutability: 'nonpayable',
      outputs: [{
        type: 'address',
        name: 'tokenTag',
        internalType: 'contract ERC1155Mock'
      }],
      name: 'create1155Pair',
      inputs: [{
        type: 'address',
        name: '_tokenSrc',
        internalType: 'address'
      }, {
        type: 'string',
        name: '_baseURI',
        internalType: 'string'
      }]
    }, {
      type: 'function',
      stateMutability: 'nonpayable',
      outputs: [{
        type: 'address',
        name: 'tokenTag',
        internalType: 'contract ERC721Mock'
      }],
      name: 'create721Pair',
      inputs: [{
        type: 'address',
        name: '_tokenSrc',
        internalType: 'address'
      }, {
        type: 'string',
        name: '_name',
        internalType: 'string'
      }, {
        type: 'string',
        name: '_symbol',
        internalType: 'string'
      }, {
        type: 'string',
        name: '_baseURI',
        internalType: 'string'
      }]
    }, {
      type: 'function',
      stateMutability: 'view',
      outputs: [{
        type: 'address',
        name: '',
        internalType: 'address'
      }],
      name: 'getPair',
      inputs: [{
        type: 'address',
        name: '',
        internalType: 'address'
      }]
    }, {
      type: 'function',
      stateMutability: 'view',
      outputs: [{
        type: 'address',
        name: '',
        internalType: 'address'
      }],
      name: 'owner',
      inputs: []
    }, {
      type: 'function',
      stateMutability: 'nonpayable',
      outputs: [],
      name: 'renounceOwnership',
      inputs: []
    }, {
      type: 'function',
      stateMutability: 'nonpayable',
      outputs: [],
      name: 'setPair',
      inputs: [{
        type: 'address',
        name: '_tokenSrc',
        internalType: 'address'
      }, {
        type: 'address',
        name: '_tokenTag',
        internalType: 'address'
      }]
    }, {
      type: 'function',
      stateMutability: 'nonpayable',
      outputs: [],
      name: 'setbridge',
      inputs: [{
        type: 'address',
        name: '_bridge',
        internalType: 'address'
      }]
    }, {
      type: 'function',
      stateMutability: 'nonpayable',
      outputs: [],
      name: 'transferOwnership',
      inputs: [{
        type: 'address',
        name: 'newOwner',
        internalType: 'address'
      }]
    }
  ],
  erc721: [
    {
      inputs: [{
        internalType: 'string',
        name: '_name',
        type: 'string'
      }, {
        internalType: 'string',
        name: '_symbol',
        type: 'string'
      }, {
        internalType: 'string',
        name: '_baseUri',
        type: 'string'
      }, {
        internalType: 'address',
        name: 'owner',
        type: 'address'
      }, {
        internalType: 'address',
        name: 'minter',
        type: 'address'
      }],
      stateMutability: 'nonpayable',
      type: 'constructor'
    }, {
      anonymous: false,
      inputs: [{
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address'
      }, {
        indexed: true,
        internalType: 'address',
        name: 'approved',
        type: 'address'
      }, {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'Approval',
      type: 'event'
    }, {
      anonymous: false,
      inputs: [{
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address'
      }, {
        indexed: true,
        internalType: 'address',
        name: 'operator',
        type: 'address'
      }, {
        indexed: false,
        internalType: 'bool',
        name: 'approved',
        type: 'bool'
      }],
      name: 'ApprovalForAll',
      type: 'event'
    }, {
      anonymous: false,
      inputs: [{
        indexed: true,
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }, {
        indexed: true,
        internalType: 'bytes32',
        name: 'previousAdminRole',
        type: 'bytes32'
      }, {
        indexed: true,
        internalType: 'bytes32',
        name: 'newAdminRole',
        type: 'bytes32'
      }],
      name: 'RoleAdminChanged',
      type: 'event'
    }, {
      anonymous: false,
      inputs: [{
        indexed: true,
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }, {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address'
      }, {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address'
      }],
      name: 'RoleGranted',
      type: 'event'
    }, {
      anonymous: false,
      inputs: [{
        indexed: true,
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }, {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address'
      }, {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address'
      }],
      name: 'RoleRevoked',
      type: 'event'
    }, {
      anonymous: false,
      inputs: [{
        indexed: true,
        internalType: 'address',
        name: 'from',
        type: 'address'
      }, {
        indexed: true,
        internalType: 'address',
        name: 'to',
        type: 'address'
      }, {
        indexed: true,
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'Transfer',
      type: 'event'
    }, {
      inputs: [],
      name: 'BURNER_ROLE',
      outputs: [{
        internalType: 'bytes32',
        name: '',
        type: 'bytes32'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [],
      name: 'DEFAULT_ADMIN_ROLE',
      outputs: [{
        internalType: 'bytes32',
        name: '',
        type: 'bytes32'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [],
      name: 'MINTER_ROLE',
      outputs: [{
        internalType: 'bytes32',
        name: '',
        type: 'bytes32'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: 'to',
        type: 'address'
      }, {
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'approve',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: 'owner',
        type: 'address'
      }],
      name: 'balanceOf',
      outputs: [{
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [],
      name: 'baseUri',
      outputs: [{
        internalType: 'string',
        name: '',
        type: 'string'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'getApproved',
      outputs: [{
        internalType: 'address',
        name: '',
        type: 'address'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }],
      name: 'getRoleAdmin',
      outputs: [{
        internalType: 'bytes32',
        name: '',
        type: 'bytes32'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }, {
        internalType: 'address',
        name: 'account',
        type: 'address'
      }],
      name: 'grantRole',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }, {
        internalType: 'address',
        name: 'account',
        type: 'address'
      }],
      name: 'hasRole',
      outputs: [{
        internalType: 'bool',
        name: '',
        type: 'bool'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: 'owner',
        type: 'address'
      }, {
        internalType: 'address',
        name: 'operator',
        type: 'address'
      }],
      name: 'isApprovedForAll',
      outputs: [{
        internalType: 'bool',
        name: '',
        type: 'bool'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: '_to',
        type: 'address'
      }, {
        internalType: 'uint256',
        name: '_tokenId',
        type: 'uint256'
      }],
      name: 'mint',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [],
      name: 'name',
      outputs: [{
        internalType: 'string',
        name: '',
        type: 'string'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'ownerOf',
      outputs: [{
        internalType: 'address',
        name: '',
        type: 'address'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }, {
        internalType: 'address',
        name: 'account',
        type: 'address'
      }],
      name: 'renounceRole',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'bytes32',
        name: 'role',
        type: 'bytes32'
      }, {
        internalType: 'address',
        name: 'account',
        type: 'address'
      }],
      name: 'revokeRole',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: 'from',
        type: 'address'
      }, {
        internalType: 'address',
        name: 'to',
        type: 'address'
      }, {
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'safeTransferFrom',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: 'from',
        type: 'address'
      }, {
        internalType: 'address',
        name: 'to',
        type: 'address'
      }, {
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }, {
        internalType: 'bytes',
        name: '_data',
        type: 'bytes'
      }],
      name: 'safeTransferFrom',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: 'operator',
        type: 'address'
      }, {
        internalType: 'bool',
        name: 'approved',
        type: 'bool'
      }],
      name: 'setApprovalForAll',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'string',
        name: '_baseURIString',
        type: 'string'
      }],
      name: 'setBaseURI',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'bytes4',
        name: 'interfaceId',
        type: 'bytes4'
      }],
      name: 'supportsInterface',
      outputs: [{
        internalType: 'bool',
        name: '',
        type: 'bool'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [],
      name: 'symbol',
      outputs: [{
        internalType: 'string',
        name: '',
        type: 'string'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'tokenURI',
      outputs: [{
        internalType: 'string',
        name: '',
        type: 'string'
      }],
      stateMutability: 'view',
      type: 'function'
    }, {
      inputs: [{
        internalType: 'address',
        name: 'from',
        type: 'address'
      }, {
        internalType: 'address',
        name: 'to',
        type: 'address'
      }, {
        internalType: 'uint256',
        name: 'tokenId',
        type: 'uint256'
      }],
      name: 'transferFrom',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function'
    }
  ],
  erc1155: [{
    inputs: [{
      internalType: 'string',
      name: '_baseUri',
      type: 'string'
    }, {
      internalType: 'address',
      name: 'owner',
      type: 'address'
    }, {
      internalType: 'address',
      name: 'minter',
      type: 'address'
    }],
    stateMutability: 'nonpayable',
    type: 'constructor'
  }, {
    anonymous: false,
    inputs: [{
      indexed: true,
      internalType: 'address',
      name: 'account',
      type: 'address'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'operator',
      type: 'address'
    }, {
      indexed: false,
      internalType: 'bool',
      name: 'approved',
      type: 'bool'
    }],
    name: 'ApprovalForAll',
    type: 'event'
  }, {
    anonymous: false,
    inputs: [{
      indexed: true,
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }, {
      indexed: true,
      internalType: 'bytes32',
      name: 'previousAdminRole',
      type: 'bytes32'
    }, {
      indexed: true,
      internalType: 'bytes32',
      name: 'newAdminRole',
      type: 'bytes32'
    }],
    name: 'RoleAdminChanged',
    type: 'event'
  }, {
    anonymous: false,
    inputs: [{
      indexed: true,
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'account',
      type: 'address'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'sender',
      type: 'address'
    }],
    name: 'RoleGranted',
    type: 'event'
  }, {
    anonymous: false,
    inputs: [{
      indexed: true,
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'account',
      type: 'address'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'sender',
      type: 'address'
    }],
    name: 'RoleRevoked',
    type: 'event'
  }, {
    anonymous: false,
    inputs: [{
      indexed: true,
      internalType: 'address',
      name: 'operator',
      type: 'address'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'from',
      type: 'address'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'to',
      type: 'address'
    }, {
      indexed: false,
      internalType: 'uint256[]',
      name: 'ids',
      type: 'uint256[]'
    }, {
      indexed: false,
      internalType: 'uint256[]',
      name: 'values',
      type: 'uint256[]'
    }],
    name: 'TransferBatch',
    type: 'event'
  }, {
    anonymous: false,
    inputs: [{
      indexed: true,
      internalType: 'address',
      name: 'operator',
      type: 'address'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'from',
      type: 'address'
    }, {
      indexed: true,
      internalType: 'address',
      name: 'to',
      type: 'address'
    }, {
      indexed: false,
      internalType: 'uint256',
      name: 'id',
      type: 'uint256'
    }, {
      indexed: false,
      internalType: 'uint256',
      name: 'value',
      type: 'uint256'
    }],
    name: 'TransferSingle',
    type: 'event'
  }, {
    anonymous: false,
    inputs: [{
      indexed: false,
      internalType: 'string',
      name: 'value',
      type: 'string'
    }, {
      indexed: true,
      internalType: 'uint256',
      name: 'id',
      type: 'uint256'
    }],
    name: 'URI',
    type: 'event'
  }, {
    inputs: [],
    name: 'DEFAULT_ADMIN_ROLE',
    outputs: [{
      internalType: 'bytes32',
      name: '',
      type: 'bytes32'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [],
    name: 'MINTER_ROLE',
    outputs: [{
      internalType: 'bytes32',
      name: '',
      type: 'bytes32'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [],
    name: 'URI_SETTER_ROLE',
    outputs: [{
      internalType: 'bytes32',
      name: '',
      type: 'bytes32'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address',
      name: 'account',
      type: 'address'
    }, {
      internalType: 'uint256',
      name: 'id',
      type: 'uint256'
    }],
    name: 'balanceOf',
    outputs: [{
      internalType: 'uint256',
      name: '',
      type: 'uint256'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address[]',
      name: 'accounts',
      type: 'address[]'
    }, {
      internalType: 'uint256[]',
      name: 'ids',
      type: 'uint256[]'
    }],
    name: 'balanceOfBatch',
    outputs: [{
      internalType: 'uint256[]',
      name: '',
      type: 'uint256[]'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }],
    name: 'getRoleAdmin',
    outputs: [{
      internalType: 'bytes32',
      name: '',
      type: 'bytes32'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }, {
      internalType: 'address',
      name: 'account',
      type: 'address'
    }],
    name: 'grantRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }, {
      internalType: 'address',
      name: 'account',
      type: 'address'
    }],
    name: 'hasRole',
    outputs: [{
      internalType: 'bool',
      name: '',
      type: 'bool'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address',
      name: 'account',
      type: 'address'
    }, {
      internalType: 'address',
      name: 'operator',
      type: 'address'
    }],
    name: 'isApprovedForAll',
    outputs: [{
      internalType: 'bool',
      name: '',
      type: 'bool'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address',
      name: 'account',
      type: 'address'
    }, {
      internalType: 'uint256',
      name: 'id',
      type: 'uint256'
    }, {
      internalType: 'uint256',
      name: 'amount',
      type: 'uint256'
    }, {
      internalType: 'bytes',
      name: 'data',
      type: 'bytes'
    }],
    name: 'mint',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address',
      name: 'to',
      type: 'address'
    }, {
      internalType: 'uint256[]',
      name: 'ids',
      type: 'uint256[]'
    }, {
      internalType: 'uint256[]',
      name: 'amounts',
      type: 'uint256[]'
    }, {
      internalType: 'bytes',
      name: 'data',
      type: 'bytes'
    }],
    name: 'mintBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }, {
      internalType: 'address',
      name: 'account',
      type: 'address'
    }],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'bytes32',
      name: 'role',
      type: 'bytes32'
    }, {
      internalType: 'address',
      name: 'account',
      type: 'address'
    }],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address',
      name: 'from',
      type: 'address'
    }, {
      internalType: 'address',
      name: 'to',
      type: 'address'
    }, {
      internalType: 'uint256[]',
      name: 'ids',
      type: 'uint256[]'
    }, {
      internalType: 'uint256[]',
      name: 'amounts',
      type: 'uint256[]'
    }, {
      internalType: 'bytes',
      name: 'data',
      type: 'bytes'
    }],
    name: 'safeBatchTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address',
      name: 'from',
      type: 'address'
    }, {
      internalType: 'address',
      name: 'to',
      type: 'address'
    }, {
      internalType: 'uint256',
      name: 'id',
      type: 'uint256'
    }, {
      internalType: 'uint256',
      name: 'amount',
      type: 'uint256'
    }, {
      internalType: 'bytes',
      name: 'data',
      type: 'bytes'
    }],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'address',
      name: 'operator',
      type: 'address'
    }, {
      internalType: 'bool',
      name: 'approved',
      type: 'bool'
    }],
    name: 'setApprovalForAll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'string',
      name: '_baseUri',
      type: 'string'
    }],
    name: 'setURI',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'bytes4',
      name: 'interfaceId',
      type: 'bytes4'
    }],
    name: 'supportsInterface',
    outputs: [{
      internalType: 'bool',
      name: '',
      type: 'bool'
    }],
    stateMutability: 'view',
    type: 'function'
  }, {
    inputs: [{
      internalType: 'uint256',
      name: '',
      type: 'uint256'
    }],
    name: 'uri',
    outputs: [{
      internalType: 'string',
      name: '',
      type: 'string'
    }],
    stateMutability: 'view',
    type: 'function'
  }
  ]
}
export default COIN_ABI
